### ISSUE TITLE
No events are emitted to Amplitude

### ISSUE THREAD

**Issue by srdjan-upstack** [amplitude/storybook-addon-amplitude#19]
Hi, I've followed the setup instructions from https://storybook.js.org/addons/@amplitude/storybook-addon-amplitude, but no data is showing in Amplitude. I've created a repro here: https://github.com/srdjan-upstack/amplitude-storybook-addon-repro

![Screenshot 2022-07-18 at 16 30 33](https://user-images.githubusercontent.com/83290283/179534526-45cadb78-6027-4de3-8b8c-12724544c786.png)

**Comment by maecapozzi** [comment]
Hi @srdjan-upstack, I took a look at your reproduction and did see that events are being emitted to Amplitude.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/11462208/180872568-a73669dc-59ad-4dd2-bf5e-f5b64c9c66fe.png">


Are you seeing events now?

**Comment by maecapozzi** [comment]
I'm going to close this since I haven't heard back from you. If you are still having trouble, feel free to open another issue.
